name: Create or Update Release on GitHub and WordPress

on:
  push:
    tags:
      - "v*" # Trigger on version tags like v1.0.0, v2.0.0-beta1

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout full repo history (important for SVN deploy)
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # fetch all commits and tags

      # 2. Display PHP & Composer info
      - name: Display PHP and Composer versions
        run: |
          php -v
          composer --version

      # 3. Install project dependencies
      - name: Install dependencies
        run: composer install

      # 4. Ensure SVN checkout is fresh (avoids "out of date" errors)
      - name: Cleanup old SVN checkout
        run: rm -rf /github/workspace/svn

      # 5. Deploy WordPress Plugin via SVN
      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@master
        env:
          SLUG: utrust-for-woocommerce
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        with:
          dry-run: false
          skip-existing: false
          verbose: true

      # 6. Build ZIP archive
      - name: Build ZIP archive
        run: |
          zip -r utrust-for-woocommerce.zip * -x .git .github composer.json composer.lock

      # 7. Create or overwrite GitHub release
      - name: Create or Update GitHub Release
        id: gh_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: false
          prerelease: ${{ contains(github.ref_name, 'beta') }}
          overwrite: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 8. Upload ZIP release asset
      - name: Upload release ZIP
        uses: softprops/action-gh-release@v1
        with:
          files: utrust-for-woocommerce.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
