name: Create or Update Release on GitHub and WordPress

on:
  push:
    tags:
      - "v*"  # Trigger on any tag starting with "v"

jobs:
  release:
    runs-on: ubuntu-latest
    # Removed container to avoid Alpine/glibc issues

    steps:
      # 1. Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # Fetch all commits and tags

      # 2. Display PHP & Composer info
      - name: Display PHP and Composer versions
        run: |
          php -v
          composer --version

      # 3. Install project dependencies
      - name: Install dependencies
        run: composer install

      # 4. WordPress Plugin Deploy via SVN
      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@master
        env:
          SLUG: utrust-for-woocommerce
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}

      # 5. Build ZIP archive
      - name: Build ZIP archive
        run: |
          zip -r utrust-for-woocommerce.zip * -x .git .github composer.json composer.lock

      # 6. Create or overwrite GitHub release
      - name: Create or Update GitHub Release
        id: gh_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          overwrite: true   # Overwrite existing release if needed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 7. Upload release ZIP
      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: utrust-for-woocommerce.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
